version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mariadb
    restart: unless-stopped
    networks:
      - laravel

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./.data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    ports:
      - "9009:9009"
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

  node:
    image: node
    container_name: node
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html # @Override: By default Node expects files inside a different directory.
    entrypoint: ["npm"]
    networks:
      - laravel

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    networks:
      - laravel
